language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

dist: trusty # to use chrome

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ./gradlew sonarqube bootJar test javadoc asciidoc -Dsonar.organization=ynojima -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build/asciidoc/html5
  target-branch: gh-pages
  on:
    branch: master
    jdk: openjdk8

addons:
  chrome: stable
  sonarcloud:
    organization: "ynojima"
